### ISSUE TITLE
NotImplemented Error

### ISSUE THREAD

**Issue by shaikhyas** [YDHCUI/CNVD-2020-10487-Tomcat-Ajp-lfi#2]
Does it mean that AJP is not enabled?

root@kali:~# python tomcatlfi.py X.X.X.X -p 8080 -f WEB-INF/web.xml
Getting resource at ajp13://X.X.X.X:8080/asdf
Traceback (most recent call last):
  File "tomcatlfi.py", line 299, in <module>
    {'name':'req_attribute','value':['javax.servlet.include.servlet_path','/']},
  File "tomcatlfi.py", line 274, in perform_request
    responses = self.forward_request.send_and_receive(self.socket, self.stream)
  File "tomcatlfi.py", line 154, in send_and_receive
    r = AjpResponse.receive(stream)
  File "tomcatlfi.py", line 225, in receive
    r.parse(stream)
  File "tomcatlfi.py", line 193, in parse
    raise NotImplementedError
NotImplementedError

**Comment by alimp5** [comment]
PS C:\Python27> .\python.exe .\aaaaaa.py 79.175.132.97 -p 8080 -f WEB-INF/web.xml
Getting resource at ajp13://79.175.132.97:8080/asdf
Traceback (most recent call last):
  File ".\aaaaaa.py", line 299, in <module>
    {'name':'req_attribute','value':['javax.servlet.include.servlet_path','/']},
  File ".\aaaaaa.py", line 274, in perform_request
    responses = self.forward_request.send_and_receive(self.socket, self.stream)
  File ".\aaaaaa.py", line 154, in send_and_receive
    r = AjpResponse.receive(stream)
  File ".\aaaaaa.py", line 225, in receive
    r.parse(stream)
  File ".\aaaaaa.py", line 193, in parse
    raise NotImplementedError
NotImplementedError

**Comment by allblue147** [comment]
8009....

**Comment by M0untainShley** [comment]
Replace -p with 8009

> 这是否意味着未启用AJP？
> 
> root@kali:~# python tomcatlfi.py XXXX -p 8080 -f WEB-INF/web.xml
> 在 ajp13://XXXX:8080/asdf 获取资源
> 回溯（最近一次调用）：
> 文件“tomcatlfi.py”，第 299 行，在
> {'name':'req_attribute','value':['javax.servlet.include.servlet_path','/']}，
> 文件“tomcatlfi.py”，第 274 行，在 perform_request
> 响应 = self. forward_request.send_and_receive(self.socket, self.stream)
> 文件“tomcatlfi.py”，第 154 行，在 send_and_receive
> r = AjpResponse.receive(stream)
> 文件“tomcatlfi.py”，第 225 行，在接收
> r.parse(stream) 中
> 文件“tomcatlfi.py”，第 193 行，在解析
> 引发 NotImplementedError
> NotImplementedError

**Comment by m4ra7h0n** [comment]
> Does it mean that AJP is not enabled?
> 
> root@kali:~# python tomcatlfi.py X.X.X.X -p 8080 -f WEB-INF/web.xml Getting resource at ajp13://X.X.X.X:8080/asdf Traceback (most recent call last): File "tomcatlfi.py", line 299, in {'name':'req_attribute','value':['javax.servlet.include.servlet_path','/']}, File "tomcatlfi.py", line 274, in perform_request responses = self.forward_request.send_and_receive(self.socket, self.stream) File "tomcatlfi.py", line 154, in send_and_receive r = AjpResponse.receive(stream) File "tomcatlfi.py", line 225, in receive r.parse(stream) File "tomcatlfi.py", line 193, in parse raise NotImplementedError NotImplementedError

it's just the tool not work

**Comment by m4ra7h0n** [comment]
8009 port bros，not 8080
