### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by biechao** [YDHCUI/CNVD-2020-10487-Tomcat-Ajp-lfi#4]
Traceback (most recent call last):
  File "test.py", line 295, in <module>
    t = Tomcat(args.target, args.port)
  File "test.py", line 261, in __init__
    self.socket.connect((target_host, target_port))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

**Comment by zhongyong** [comment]
https  ok？
Traceback (most recent call last):
  File "CNVD-2020-10487-Tomcat-Ajp-lfi.py", line 299, in <module>
    {'name':'req_attribute','value':['javax.servlet.include.servlet_path','/']},
  File "CNVD-2020-10487-Tomcat-Ajp-lfi.py", line 274, in perform_request
    responses = self.forward_request.send_and_receive(self.socket, self.stream)
  File "CNVD-2020-10487-Tomcat-Ajp-lfi.py", line 154, in send_and_receive
    r = AjpResponse.receive(stream)
  File "CNVD-2020-10487-Tomcat-Ajp-lfi.py", line 225, in receive
    r.parse(stream)
  File "CNVD-2020-10487-Tomcat-Ajp-lfi.py", line 193, in parse
    raise NotImplementedError
NotImplementedError
